module.exports = [
    {
      captainName: "Picard",
      title: "Courage",
      post: "Courage can be an emotion too.",
      mistakesWereMadeToday: true,
      daysSinceLastCrisis: 100,
    },
    {
      captainName: "Morgan",
      title: "Mixed with Ginger-Ale",
      post: "Spice it Up.",
      mistakesWereMadeToday: true,
      daysSinceLastCrisis: 2,
    },
    {
      captainName: "Jack Sparrow",
      title: "Honesty?",
      post: `I'm dishonest, and a dishonest man you can always trust to be dishonest. Honestly. It's the honest ones you want to watch out for, because you can never predict when they're going to do something incredibly … stupid.`,
      mistakesWereMadeToday: true,
      daysSinceLastCrisis: 0,
    },
    {
      captainName: "Crunch",
      title: "Berries",
      post: "Do I like them enough...?",
      mistakesWereMadeToday: false,
      daysSinceLastCrisis: 100,
    },
    {
      captainName: "Kirk",
      title: "Choices",
      post: "Without Freedom Of Choice There Is No Creativity. The Body Dies.",
      mistakesWereMadeToday: false,
      daysSinceLastCrisis: 0,
    },
    {
      captainName: "Hook",
      title: "Who was that Imposter?",
      post: "I don't understand. Why doesn't he fly? Is he not Peter Pan?",
      mistakesWereMadeToday: true,
      daysSinceLastCrisis: 43,
    },
    {
      captainName: "Han Solo",
      title: "Princess who?",
      post: "Look, Your Worshipfulness, let's get one thing straight. I take orders from just one person: me.",
      mistakesWereMadeToday: true,
      daysSinceLastCrisis: 0,
    },
  ];