module.exports = [
  {
    captainName: "Picard",
    title: "Courage",
    post: "Courage can be an emotion too.",
    mistakesWereMadeToday: true,
    daysSinceLastCrisis: 100,
  },
  {
    captainName: "Ahab",
    title: "Whale",
    post: "By heavens man, we are turned round and round in this world, like yonder windlass, and fate is the handspike.",
    mistakesWereMadeToday: true,
    daysSinceLastCrisis: 20,
  },
  {
    captainName: "Sarah Lance",
    title: "Vandal Savage",
    post: "I’d tell you to go to hell, but you’d probably just feel at home there.",
    mistakesWereMadeToday: true,
    daysSinceLastCrisis: 0,
  },
  {
    captainName: "Ahab",
    title: "Insolence",
    post: "I don't give reasons. I give orders!",
    mistakesWereMadeToday: true,
    daysSinceLastCrisis: 100,
  },
  {
    captainName: "Sarah Lance",
    title: "Ava",
    post: "Ava's the kind of girl that you take home to your parents, and I am the kind you take to an exorcism",
    mistakesWereMadeToday: true,
    daysSinceLastCrisis: 0,
  },
  {
    captainName: "Ahab",
    title: "What is sleep?",
    post: "Sleep? That bed is a coffin, and those are winding sheets. I do not sleep, I die.",
    mistakesWereMadeToday: true,
    daysSinceLastCrisis: 5,
  },
  {
    captainName: "Sarah Lance",
    title: "Jonah Hex",
    post: "I know you don’t like taking orders from a woman, but you’re gonna like getting your ass kicked by one even less.",
    mistakesWereMadeToday: true,
    daysSinceLastCrisis: 0,
  },
  {
    captainName: "Morgan",
    title: "Mixed with Ginger-Ale",
    post: "Spice it Up.",
    mistakesWereMadeToday: true,
    daysSinceLastCrisis: 2,
  },
  {
    captainName: "Jack Sparrow",
    title: "Honesty?",
    post: `I'm dishonest, and a dishonest man you can always trust to be dishonest. Honestly. It's the honest ones you want to watch out for, because you can never predict when they're going to do something incredibly … stupid.`,
    mistakesWereMadeToday: true,
    daysSinceLastCrisis: 0,
  },
  {
    captainName: "Crunch",
    title: "Berries",
    post: "Do I like them enough...?",
    mistakesWereMadeToday: false,
    daysSinceLastCrisis: 100,
  },
  {
    captainName: "Kirk",
    title: "Choices",
    post: "Without Freedom Of Choice There Is No Creativity. The Body Dies.",
    mistakesWereMadeToday: false,
    daysSinceLastCrisis: 0,
  },
  {
    captainName: "Hook",
    title: "Who was that Imposter?",
    post: "I don't understand. Why doesn't he fly? Is he not Peter Pan?",
    mistakesWereMadeToday: true,
    daysSinceLastCrisis: 43,
  },
  {
    captainName: "Han Solo",
    title: "Princess who?",
    post: "Look, Your Worshipfulness, let's get one thing straight. I take orders from just one person: me.",
    mistakesWereMadeToday: true,
    daysSinceLastCrisis: 0,
  },
];
